### PR TITLE
cicd: multi platform support

### PR DESCRIPTION
**Pull request by nomagick**

### CODE REVIEW

**Review by mapleeit — APPROVED** [review]

**Comment by mapleeit** [comment]
Let's create a new release and see if that works. @nomagick

**Comment by nomagick** [comment]
When you merge to master, it is already pushed to latest automatically.
So I guess you can simply `jina hub pull jinahub+docker://SimpleIndexer/latest --force` on M1/M2 to see if you get a native image?

**Comment by mapleeit** [comment]
```
> docker inspect b74ef4d06d02
[
    {
        "Id": "sha256:b74ef4d06d029484a3a1bab4177747e738368b38982b86d6205d208bcaa30577",
        "RepoTags": [
            "jinahub/zb38xlt4:6406a302515e5f9e7170a0c7"
        ],
        "RepoDigests": [
            "jinahub/zb38xlt4@sha256:187a9b8ee4c1b93aa2ba6023492f5c6a9365fdcd284b28092241b7cc2e7a3e13"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-03-07T02:35:47.900362556Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.7.16",
                "PYTHON_PIP_VERSION=22.0.4",
                "PYTHON_SETUPTOOLS_VERSION=57.5.0",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/1a96dc5acd0303c4700e02655aefd3bc68c78958/public/get-pip.py",
                "PYTHON_GET_PIP_SHA256=d1d09b0f9e745610657a528689ba3ea44a73bd19c60f4c954271b790c71c2653",
                "PIP_NO_CACHE_DIR=1",
                "PIP_DISABLE_PIP_VERSION_CHECK=1",
                "JINA_PIP_INSTALL_CORE=",
                "JINA_PIP_INSTALL_PERF=1",
                "JINA_VERSION=3.14.1",
                "JINA_VCS_VERSION=refs/tags/v3.14.1",
                "JINA_BUILD_DATE=2023-02-24T10:22:42Z"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/workspace",
            "Entrypoint": [
                "jina",
                "executor",
                "--uses",
                "config.yml"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.authors": "hello@jina.ai",
                "org.opencontainers.image.created": "2023-02-24T10:22:42Z",
                "org.opencontainers.image.description": "Build multimodal AI services via cloud native technologies",
                "org.opencontainers.image.documentation": "https://docs.jina.ai",
                "org.opencontainers.image.licenses": "Apache 2.0",
                "org.opencontainers.image.revision": "refs/tags/v3.14.1",
                "org.opencontainers.image.source": "https://github.com/jina-ai/jina/commit/refs/tags/v3.14.1",
                "org.opencontainers.image.title": "Jina",
                "org.opencontainers.image.url": "https://github.com/jina-ai/jina",
                "org.opencontainers.image.vendor": "Jina AI Limited",
                "org.opencontainers.image.version": "3.14.1"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 283179266,
        "VirtualSize": 283179266,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ce0975fb24cddad4f12ca4129ed79da0541ba2040323d800d13547887c00b8b9/diff:/var/lib/docker/overlay2/f524079de1efc46a2275140e0c88ce71a6e29d5487f7196b574cc4ee271ae409/diff:/var/lib/docker/overlay2/31aaa3b13b4bc7b467c7d93f23f42e8c3f0b64ce1542f0d51d6c9d4901c87aa1/diff:/var/lib/docker/overlay2/4a624caa67bfaf01c2d02d7ae492e2b40bcc57e6ddbf109cfac8eba101ee337d/diff:/var/lib/docker/overlay2/e515a531fc998f9e145557c71e0429341b36cac77c984601a2e83b78aa9abeee/diff:/var/lib/docker/overlay2/d35cc5d11274fc91e0616233baa3c049e52c4041de34732c0a9fd8470c8112ca/diff:/var/lib/docker/overlay2/c48c898054eaf0a696737ff06a9428e34fdbb698c734743a313c43be1729da26/diff:/var/lib/docker/overlay2/b8a1244b9f8b61da442ecff36434222a2150e3c2f3989678614ec50708aaaf45/diff:/var/lib/docker/overlay2/a7d2c1c85c5d0432357bf1cff409efd30b23f7028f4d1472cc54d80a6454835f/diff:/var/lib/docker/overlay2/8505f82a56a7f55c7e749170ee3314ca2d58b072472d1eec270e138994f7a773/diff",
                "MergedDir": "/var/lib/docker/overlay2/a441681259861d66533501cf42f670a9cd79e89ed42b861f39a7701a4c5553cc/merged",
                "UpperDir": "/var/lib/docker/overlay2/a441681259861d66533501cf42f670a9cd79e89ed42b861f39a7701a4c5553cc/diff",
                "WorkDir": "/var/lib/docker/overlay2/a441681259861d66533501cf42f670a9cd79e89ed42b861f39a7701a4c5553cc/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:4695cdfb426a05673a100e69d2fe9810d9ab2b3dd88ead97c6a3627246d83815",
                "sha256:36e5ac463d7db25169488dfa317279a84bf21459674fb83b58cd99f4b2264171",
                "sha256:74f81c76fe4c70bf8fa965caf63a103f997126cc9ed2d7a57e7a61842152e813",
                "sha256:69bf6df475b3c777ed12626a0c84092c4dd6a7ed3185652bd5c93f17d7d41c79",
                "sha256:ccc3f0523c25f6418020220db6401fda3a8af16dc934134a9246461e24ea6880",
                "sha256:ae738854472e50edfa40aeed9b485ba03b1c0521aee3b11303ed4badfb635b84",
                "sha256:c7b92bf11342469501f1284d3f669d7be8401c98b645d6367c55f72192748c9d",
                "sha256:fb5526fae2c5f5cedaaba01ed7f6fcfd26841815635fa73ee61d00a62fc4aded",
                "sha256:7c9461e214ae60423c6aa7b078e31468b0d6613e637a2e58574c58d8d56c09ae",
                "sha256:d05032f4c8a5287b6124fd1f67d43f75752ac16cfc1f1332910db11861d56431",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

It's still `amd64` on my M1 machine. Anything wrong?

**Comment by nomagick** [comment]
This had something to do with pushing with both `--force` and `--secret` and it fell back to the old API which does not have multiplatform support.
I'll fix and deprecate the `--secret`.

**Comment by nomagick** [comment]
This had something to do with pushing with both `--force` and `--secret` and it fell back to the old API which does not have multiplatform support.
I'll fix and deprecate the `--secret`.

**Pull request merged**
